### ISSUE TITLE
@import "normalize"; not works in app/styles/app.scss

### ISSUE THREAD

**Issue by siriniok** [HeroicEric/ember-normalize#2]
But @import "normalize.css"; works perfectly.

**Comment by HeroicEric** [comment]
@siriniok do you have a sass preprocessor setup? Which one?

**Comment by siriniok** [comment]
@HeroicEric yes, of course. I have `"ember-cli-sass": "3.3.1"`.

**Comment by HeroicEric** [comment]
@siriniok Can you provide an example app? I can't replicate this.
